"""Plugin Generator - AI generates new plugins automatically.

Jiro detects a need for a new plugin, generates the code,
saves it to the plugins/ folder, and it auto-loads.
"""

import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger("jiro.plugins.generator")

PLUGINS_DIR = Path(__file__).parent
PLUGIN_TEMPLATE = '''"""Auto-generated plugin: {name}

Generated by Jiro AI Plugin Generator.
"""

from plugins.plugin_loader import PluginBase


class {class_name}(PluginBase):
    name = "{name}"
    description = "{description}"
    triggers = {triggers}
    version = "1.0.0"
    requires_api_keys = {api_keys}

    async def execute(self, command, context=None):
{execute_body}
'''


class PluginGenerator:
    """Generates new plugins using AI."""

    def __init__(self, config: dict, ai_engine=None):
        self._config = config
        self._ai_engine = ai_engine

    async def generate_plugin(self, description: str, name: Optional[str] = None) -> Optional[Path]:
        """Generate a new plugin from a description."""
        if not self._ai_engine:
            logger.error("AI engine required for plugin generation")
            return None

        if not name:
            name = self._sanitize_name(description)

        prompt = (
            f"Generate a Python plugin class for Jiro AI assistant.\n\n"
            f"Description: {description}\n\n"
            f"Requirements:\n"
            f"- Import PluginBase from plugins.plugin_loader\n"
            f"- Create a class inheriting from PluginBase\n"
            f"- Set name, description, triggers (list of keywords)\n"
            f"- Implement async execute(self, command, context=None) -> str\n"
            f"- The execute method should handle the described functionality\n"
            f"- Use self.config for config access, self.ai_engine for AI\n\n"
            f"Return ONLY the Python code, no markdown or explanation."
        )

        try:
            code = await self._ai_engine.process(prompt)

            if "```python" in code:
                code = code.split("```python")[1].split("```")[0].strip()
            elif "```" in code:
                code = code.split("```")[1].split("```")[0].strip()

            if "PluginBase" not in code or "class " not in code:
                logger.error("Generated code doesn't look like a valid plugin")
                return None

            file_name = f"{name}_plugin.py"
            file_path = PLUGINS_DIR / file_name

            file_path.write_text(code)
            logger.info("Plugin generated: %s", file_path)
            return file_path

        except Exception as e:
            logger.error("Plugin generation failed: %s", e)
            return None

    def _sanitize_name(self, description: str) -> str:
        words = re.sub(r'[^a-zA-Z\s]', '', description.lower()).split()
        return "_".join(words[:3]) if words else "custom"

    def list_generated(self) -> list[str]:
        """List all auto-generated plugins."""
        generated = []
        for path in PLUGINS_DIR.glob("*_plugin.py"):
            try:
                content = path.read_text()
                if "Auto-generated plugin" in content or "Generated by Jiro AI" in content:
                    generated.append(path.stem)
            except Exception:
                pass
        return generated
